name: Java Image Conversion

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: List files (debug)
        run: ls -la

      - name: Compile Java
        run: javac ColorToGray.java

      - name: Run Java converter
        run: java -Djava.awt.headless=true ColorToGray color_image.jpg grayscale_image.jpg

      - name: Upload output image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: grayscale-image
          path: grayscale_image.jpg
